title: "Apollo"
description: "A personal website builder template."
baseurl: "" # e.g., /blog
url: "https://apollo.vikash.me" # Base URL
profile_image: "/assets/images/profile.jpg"

# Jekyll Settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  publications:
    output: true
    permalink: /publications/:title/
    directory: content/_publications

# Site Navigation and Overrides
site:
  title: "My Personal Website"
  navigation:
    - name: "Home"
      url: "/"
    - name: "Blog"
      url: "/blog/"
    - name: "Publications"
      url: "/publications/"
  footer_links:
    - name: "Contact"
      url: "/contact/"
    - name: "About"
      url: "/about/"
  overrides:
    css: "main.css"
    js: "main.min.js"

# Content Repository
content_repo: "https://github.com/yourusername/content-repo.git"

# Directory Configurations
layouts_dir: _layouts
includes_dir: _includes
posts_dir: content/_posts
destination: _site 