title: Apollo
description: A personal website generator

# Content Settings
content:
  source: "local"           # "local" for content/ directory, "external" for git submodule/repo
  repository: ""            # Git URL if using external content

# Site Settings  
user:
  name: "Your Name"
  domain: ""
  description: "A personal website"

# Optional Features
features:
  google_scholar:
    enabled: false
    user_id: ""

# Jekyll Settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
  - LICENSE
  - tailwind.config.js
  - package.json
  - package-lock.json
  - user-config.yml
  - build.sh
  - setup.sh
  - sync-content.sh
  - _site-config.yml
  - FEATURES.md

include:
  - content

collections:
  posts:
    output: true
    permalink: /essays/:slug/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      layout: "default"