title: Apollo
description: A personal website generator

# Content Settings
content:
  source: "local"           # "local" for content/ directory, "external" for git submodule/repo
  repository: ""            # Git URL if using external content

# Site Settings  
user:
  name: "Your Name"
  domain: ""
  description: "A personal website"

# Jekyll Settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
  - LICENSE
  - tailwind.config.js
  - package.json
  - package-lock.json
  - user-config.yml
  - build.sh
  - setup.sh
  - sync-content.sh
  - _site-config.yml
  - FEATURES.md
  - app.yaml
  - .gcloudignore
  - DEPLOYMENT.md
  - scripts/
  - main.py
  - requirements.txt

include:
  - content

collections:
  essays:
    output: true
    permalink: /essays/:slug/

# Configure collections to be in content/
collections_dir: content

defaults:
  -
    scope:
      path: ""
      type: "essays"
    values:
      layout: "essay"
  -
    scope:
      path: ""
    values:
      layout: "default"