title: "Apollo"
description: "A personal website builder template."
baseurl: "" # the subpath of your site, e.g., /blog
url: "https://apollo.vikash.me" # the base hostname & protocol for your site

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
overrides:
  header: "custom_header.html"