runtime: go122

handlers:
  # Serve all static files with urls ending with a file extension
  - url: /(.*\..*)$
    static_files: _site/\1
    upload: _site/(.*\..*)$

  # Catch all handler to index.html
  - url: /.*
    static_files: _site/index.html
    upload: _site/index.html