runtime: python39

# Static file handlers for Jekyll site
handlers:
# Handle root index explicitly first
- url: /
  static_files: _site/index.html
  upload: _site/index.html

# Handle assets (CSS, JS, images)
- url: /assets/(.*)
  static_files: _site/assets/\1
  upload: _site/assets/.*

# Handle feed.xml
- url: /feed\.xml
  static_files: _site/feed.xml
  upload: _site/feed.xml

# Handle sitemap.xml (if it exists)
- url: /sitemap\.xml
  static_files: _site/sitemap.xml
  upload: _site/sitemap.xml

# Handle robots.txt (if it exists)
- url: /robots\.txt
  static_files: _site/robots.txt
  upload: _site/robots.txt

# Handle Jekyll pretty URLs - directories with trailing slash
- url: /(.+)/$
  static_files: _site/\1/index.html
  upload: _site/.*/index.html

# Handle Jekyll pretty URLs - directories without trailing slash
- url: /([^/]+)$
  static_files: _site/\1/index.html
  upload: _site/.*/index.html

# Handle direct HTML files
- url: /(.+)\.html$
  static_files: _site/\1.html
  upload: _site/.*\.html

# Catch-all for any other files
- url: /(.*)
  static_files: _site/\1
  upload: _site/.*

# Error handlers
error_handlers:
- file: _site/404.html
  error_code: over_quota
- file: _site/404.html
  error_code: dos_api_denial
- file: _site/404.html
  error_code: timeout

# Performance and security settings
automatic_scaling:
  min_instances: 0
  max_instances: 10

# Security headers for static content
env_variables:
  SECURE_SSL_REDIRECT: "true"