runtime: python39

# This is a placeholder main.py that will never be called
# since all requests are handled by static file handlers

handlers:
# Handle root index
- url: /
  static_files: _site/index.html
  upload: _site/index.html

# Handle assets
- url: /assets/(.*)
  static_files: _site/assets/\1
  upload: _site/assets/.*

# Handle feed
- url: /feed\.xml
  static_files: _site/feed.xml
  upload: _site/feed.xml

# Handle Jekyll pretty URLs with trailing slash
- url: /(.+)/
  static_files: _site/\1/index.html
  upload: _site/.*/index.html

# Handle Jekyll pretty URLs without trailing slash
- url: /([^/\.]+)
  static_files: _site/\1/index.html
  upload: _site/.*/index.html

# Handle HTML files directly
- url: /(.+\.html)
  static_files: _site/\1
  upload: _site/.*\.html

# Catch-all for other files
- url: /(.*)
  static_files: _site/\1
  upload: _site/.*

# Fallback to a basic Python app for any unmatched requests
- url: /.*
  script: auto

error_handlers:
- file: _site/404.html