runtime: python39

# This is a placeholder main.py that will never be called
# since all requests are handled by static file handlers

handlers:
# Handle assets with static_dir (more reliable for directories)
- url: /assets
  static_dir: _site/assets

# Handle root index
- url: /
  static_files: _site/index.html
  upload: _site/index.html

# Handle feed
- url: /feed\.xml
  static_files: _site/feed.xml
  upload: _site/feed.xml

# Handle Jekyll pretty URLs with trailing slash
- url: /(.+)/$
  static_files: _site/\1/index.html
  upload: _site/.*/index.html

# Handle Jekyll pretty URLs without trailing slash
- url: /([^/\.]+)$
  static_files: _site/\1/index.html
  upload: _site/.*/index.html

# Handle HTML files directly
- url: /(.+\.html)$
  static_files: _site/\1
  upload: _site/.*\.html

# Catch-all for other files
- url: /(.*)
  static_files: _site/\1
  upload: _site/.*

error_handlers:
- file: _site/404.html
  error_code: over_quota
- file: _site/404.html
  error_code: dos_api_denial  
- file: _site/404.html
  error_code: timeout

# Performance and security settings
automatic_scaling:
  min_instances: 0
  max_instances: 10

# Security headers for static content
env_variables:
  SECURE_SSL_REDIRECT: "true"