runtime: python39

# This is a placeholder main.py that will never be called
# since all requests are handled by static file handlers

handlers:
# Handle assets with static_dir (more reliable for directories)
- url: /assets
  static_dir: _site/assets

# Handle root index explicitly
- url: /
  static_files: _site/index.html
  upload: _site/index\.html

# Handle feed
- url: /feed\.xml
  static_files: _site/feed.xml
  upload: _site/feed\.xml

# Handle 404 page
- url: /404\.html
  static_files: _site/404.html
  upload: _site/404\.html

# Handle specific known paths first
- url: /about/?
  static_files: _site/about/index.html
  upload: _site/about/index\.html

- url: /essays/?
  static_files: _site/essays/index.html
  upload: _site/essays/index\.html

# Handle Jekyll pretty URLs with trailing slash
- url: /([^/.]+)/?$
  static_files: _site/\1/index.html
  upload: _site/.*/index\.html

# Handle nested Jekyll pretty URLs
- url: /([^/.]+)/([^/.]+)/?$
  static_files: _site/\1/\2/index.html
  upload: _site/.*/index\.html

# Handle HTML files directly
- url: /(.+\.html)$
  static_files: _site/\1
  upload: _site/.*\.html$

# Catch-all for other static files
- url: /(.+)$
  static_files: _site/\1
  upload: _site/.*

error_handlers:
- file: _site/404.html
  error_code: over_quota
- file: _site/404.html
  error_code: dos_api_denial  
- file: _site/404.html
  error_code: timeout

# Performance and security settings
automatic_scaling:
  min_instances: 0
  max_instances: 10

# Security headers for static content
env_variables:
  SECURE_SSL_REDIRECT: "true"