runtime: python39

# Static file handlers for Jekyll site
handlers:
# Handle assets (CSS, JS, images)
- url: /assets
  static_dir: _site/assets
  secure: always

# Handle feed.xml and sitemap.xml
- url: /(feed|sitemap)\.xml
  static_files: _site/\1.xml
  upload: _site/(feed|sitemap)\.xml
  secure: always

# Handle robots.txt
- url: /robots\.txt
  static_files: _site/robots.txt
  upload: _site/robots\.txt
  secure: always

# Handle root index
- url: /
  static_files: _site/index.html
  upload: _site/index.html
  secure: always

# Handle directories with trailing slash (Jekyll pretty URLs)
- url: /(.+)/
  static_files: _site/\1/index.html
  upload: _site/.*/index.html
  secure: always

# Handle direct HTML files
- url: /(.+)\.html
  static_files: _site/\1.html
  upload: _site/.*\.html
  secure: always

# Catch-all for any other static files
- url: /(.+)
  static_files: _site/\1
  upload: _site/.*
  secure: always

# Error handlers
error_handlers:
- file: _site/404.html
  error_code: over_quota
- file: _site/404.html
  error_code: dos_api_denial
- file: _site/404.html
  error_code: timeout

# Performance and security settings
automatic_scaling:
  min_instances: 0
  max_instances: 10

# Security headers for static content
env_variables:
  SECURE_SSL_REDIRECT: "true"