runtime: go122

handlers:
  # Serve static assets like CSS, JS, images
  - url: /assets
    static_dir: build/assets/
    secure: always
    http_headers:
      Cache-Control: "public, max-age=31536000"

  - url: /images
    static_dir: build/images/
    secure: always
    http_headers:
      Cache-Control: "public, max-age=31536000"

  - url: /_overrides
    static_dir: override/
    secure: always
    http_headers:
      Cache-Control: "public, max-age=31536000"

  # Serve all other routes with default.html
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
    secure: always
    http_headers:
      Cache-Control: "public, max-age=600"