title: "Apollo"
description: "A personal website builder template."
baseurl: "" # e.g., /blog
url: "https://apollo.vikash.me" # Base URL
profile_image: "/assets/images/profile.jpg"

# Jekyll Settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Site Navigation and Overrides
site:
  title: "My Personal Website"
  navigation:
    - name: "Home"
      url: "/home/"
    - name: "Blog"
      url: "/blog/"
    - name: "Publications"
      url: "/publications/"
  footer_links:
    - name: "Contact"
      url: "/contact/"
    - name: "About"
      url: "/about/"
  # overrides:
  #   css: "styles.min.css"
  #   js: "main.min.js"

# Permalink settings for clean URLs
permalink: pretty

# Directory Configurations
layouts_dir: _layouts
includes_dir: _includes
posts_dir: content/blogs
destination: build/